# Generated by Django 5.0.7 on 2024-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('img_url', models.URLField(blank=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('img_url', models.URLField(blank=True)),
                ('description', models.CharField(max_length=500)),
                ('org_type', models.CharField(choices=[('SCHOOL_BOARD', 'School Board'), ('PARTY', 'Party'), ('CITY_COUNCIL', 'City Council')], max_length=100)),
                ('agenda', models.URLField(blank=True)),
                ('members', models.ManyToManyField(related_name='organizations', to='common.politician')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
