# Generated by Django 5.0.7 on 2024-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', to='common.politician'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL_BOARD', 'School Board'), ('PARTY', 'Party'), ('CITY_COUNCIL', 'City Council')], default='Party', max_length=100),
            preserve_default=False,
        ),
    ]
