# Generated by Django 5.0.7 on 2024-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_members_organization_org_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='links',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='links',
        ),
        migrations.AddField(
            model_name='organization',
            name='agenda',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='ProfileLinks',
        ),
    ]
