# Generated by Django 5.0.7 on 2024-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_organization_fax_politician_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL_BOARD', 'School Board'), ('PARTY', 'Party'), ('CITY_COUNCIL', 'City Council'), ('COUNTY_COUNCIL', 'County Council')], max_length=100),
        ),
    ]
