# Generated by Django 5.0.7 on 2024-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_organization_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='common.politician'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('preview', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('related', models.ManyToManyField(blank=True, related_name='articles', to='common.politician')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
