# Generated by Django 5.0.7 on 2024-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL_BOARD', 'School Board'), ('PARTY', 'Party'), ('CITY_COUNCIL', 'City Council'), ('COUNTY_COUNCIL', 'County Council'), ('STATE_COUNCIL', 'State Council'), ('US_CONGRESS', ' US Congress')], max_length=100),
        ),
    ]
