# Generated by Django 5.0.7 on 2024-08-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_organization_org_type'),
        ('common', '0010_politician_party_alter_organization_org_type'),
    ]

    operations = [
    ]
