# Generated by Django 5.0.7 on 2024-08-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_merge_20240805_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='politician',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
