# Generated by Django 5.0.7 on 2024-08-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_organization_views_politician_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL_BOARD', 'School Board'), ('PARTY', 'Party'), ('CITY_COUNCIL', 'City Council'), ('COUNTY_COUNCIL', 'County Council'), ('STATE_GOVERNMENT', 'State Government'), ('US_CONGRESS', ' US Congress')], max_length=100),
        ),
    ]
